/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 148
#define YY_END_OF_BUFFER 149
static yyconst short int yy_accept[501] =
    {   0,
       65,   65,    0,    0,    0,    0,    0,    0,  149,  147,
      145,  146,  146,    3,  147,  142,  147,   12,    5,  147,
      147,    8,    9,   14,   10,   13,   11,   64,   64,  147,
        1,    7,    2,  147,  123,  134,    4,  123,  123,  123,
      123,  123,  123,  123,  123,  123,  123,  123,  123,  123,
      123,  123,  123,  123,  123,  123,  123,  147,    6,  137,
      138,  137,  137,  141,  140,  140,  144,  143,  143,   40,
        0,   69,  124,  131,   30,  128,   37,   29,    0,   70,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   33,
       55,   64,   35,   54,   34,  110,   31,  135,  139,   32,

        0,  133,  126,   43,   44,   40,    0,   41,  111,   42,
       45,  123,   27,  123,  123,  123,  123,   81,  123,  123,
      123,  123,  123,  123,  123,   72,  123,  123,  123,  123,
      123,  123,  123,  123,  123,  123,  123,   59,  123,  123,
      123,  123,  123,  123,   21,  123,  123,  123,  123,  123,
      123,  123,  123,  123,  123,  123,  123,  132,   28,   36,
      136,   38,  124,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   63,  127,  129,   26,    0,   39,   25,  123,
      123,  123,  123,  123,  123,  123,  123,   23,  123,  123,
      123,  123,  123,  123,  123,  123,  123,  123,   58,  123,

      123,  123,  123,  123,  123,  123,  123,   75,  123,  123,
      123,  123,  123,  123,  123,  123,  123,  123,   57,  123,
      123,  123,  123,  123,  123,  123,  123,   92,  123,   95,
      103,  123,   22,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  123,  123,  123,  123,  123,  123,  123,
      123,  123,  123,  123,   84,  123,  123,  123,  123,  123,
      123,  123,  123,   71,   61,  123,  123,  123,  123,  123,
      123,   18,  123,  123,  123,  123,  123,   88,  123,  123,
      123,  123,  123,  112,  123,  123,  123,  123,  123,  123,
      123,  123,  123,  123,  123,  123,    0,    0,    0,    0,

       53,    0,    0,    0,    0,    0,  126,  123,  123,  123,
      123,  123,  123,  123,  123,  123,  113,   86,   93,  123,
       15,   56,   90,  123,  123,  123,  123,  106,  123,  123,
       62,  123,  123,  123,  100,  123,  123,  123,  123,  123,
      123,  123,  105,  123,   24,  123,  123,  123,  123,  123,
      123,  123,   94,  104,   73,    0,   48,    0,    0,    0,
        0,    0,   52,    0,    0,  123,  123,  123,  123,  123,
      123,  123,  123,  123,  123,  123,  123,  123,   60,  123,
       76,  123,  123,  123,  123,  123,   96,  123,  123,  123,
      123,  123,  123,  123,   97,  123,   91,  102,   82,   50,

        0,    0,    0,    0,    0,   47,  123,  122,  123,  123,
      123,  123,  123,  123,  123,  123,  123,   79,   85,  123,
      123,  123,  123,  108,   77,  123,  123,   20,  123,  123,
      123,   99,  123,   17,    0,    0,   49,   51,  123,  119,
      123,  118,  123,  123,  123,  101,  123,   87,  123,  123,
      123,   74,   89,  123,  123,  123,  123,  123,  123,  123,
      115,  123,  123,  123,  123,  123,  123,   83,  123,  123,
      123,  107,  120,   98,  123,  123,  116,  123,  123,   80,
       78,  109,  123,   46,  123,  123,  123,  123,  123,  123,
      117,  123,  123,   19,   16,  121,  123,  123,  114,    0

    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   22,    1,   23,
       24,   25,   26,    1,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   33,   33,   36,   37,   38,   39,   40,
       33,   41,   42,   43,   44,   33,   33,   45,   33,   33,
        1,   46,    1,   47,   48,    1,   49,   50,   51,   52,

       53,   54,   55,   56,   57,   58,   59,   60,   61,   62,
       63,   64,   65,   66,   67,   68,   69,   70,   71,   72,
       73,   33,   74,   75,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[76] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        2,    1,    1,    1,    1,    1,    3,    3,    3,    3,
        3,    3,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    1,    1,    4,    3,    3,
        3,    3,    3,    3,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    5,    1
    } ;

static yyconst short int yy_base[510] =
    {   0,
        0,    0,   73,   75,   77,   79,   81,   87,  570,  571,
      571,  571,  571,  545,  562,  571,  493,   68,   76,  555,
       45,  541,   83,  571,   96,  540,   82,   89,   98,  541,
      106,   98,  100,  537,    0,  571,  537,  512,   76,  493,
       86,   84,   93,   70,   85,   97,  501,  103,  491,   91,
      503,   98,  106,  106,  506,  498,  490,  544,  104,  571,
      571,  571,  532,  571,  571,  571,  571,  571,  571,  526,
      543,  571,    0,  571,  571,  571,  571,  571,  537,  571,
      481,  483,  482,  484,  481,  492,  488,  472,  477,  571,
      571,  150,  571,  571,  571,  571,  571,  571,  571,  571,

        0,  571,  514,  151,  571,  571,  112,  513,  571,  571,
      512,    0,  571,  148,  468,  482,  467,    0,  479,  114,
      462,  134,  468,  136,  476,    0,  472,  460,  462,  473,
      475,  131,  461,  456,  459,  457,  451,    0,  454,  138,
      450,  449,  454,  443,    0,  135,  463,  126,  463,  454,
      444,  436,  441,  454,  440,  448,  438,  571,  571,  571,
      571,  571,    0,  437,  439,  432,  437,  431,  440,  448,
      430,  428,    0,  571,  571,  571,  438,  571,  571,  457,
      457,  158,  456,  459,  462,  439,  419,    0,  437,  436,
      431,  432,  420,  414,  418,  128,  419,  429,    0,  414,

      423,  407,  155,  414,  405,  419,  422,  417,  418,  418,
      404,  406,  405,  396,  410,  409,  393,  407,    0,  138,
      391,  398,  388,  387,  387,  386,  390,    0,  399,    0,
        0,  391,    0,  401,  389,  398,  398,  188,  393,  385,
      387,  390,  378,  414,  399,  403,  400,  399,  393,  398,
      374,  367,  359,  372,    0,  374,  378,  361,  374,  358,
      368,  375,  354,    0,  365,  348,  367,  356,  364,  346,
      360,    0,  353,  354,  364,  344,  362,    0,  357,  340,
      359,  341,  338,    0,  338,  336,  354,  349,  344,  343,
      333,  341,  346,  325,  327,  341,  320,  190,  332,  323,

      571,  335,  338,  375,  325,  318,  571,  343,  336,  352,
      353,  350,  346,  348,  310,  328,    0,    0,    0,  308,
        0,    0,    0,  313,  308,  313,  318,    0,  320,  304,
        0,  312,  311,  315,    0,  315,  308,  304,  302,  310,
      299,  306,    0,  295,    0,  290,  306,  305,  289,  292,
      302,  296,    0,    0,    0,  338,  571,  301,  296,  335,
      294,  278,  571,  290,  331,  301,  294,  293,  297,  291,
      299,  295,  288,  284,  277,  264,  279,  263,    0,  270,
      276,  260,  267,  259,  269,  261,    0,  270,  269,  270,
      271,  270,  265,  249,    0,  263,    0,    0,    0,  571,

      253,  301,  247,  299,  298,  571,  262,    0,  261,  273,
      259,  276,  265,  253,  235,  239,  248,    0,    0,  251,
      250,  247,  244,    0,    0,  234,  233,  246,  240,  241,
      240,    0,  237,  241,  275,  274,  571,  571,  238,    0,
      246,    0,  236,  256,  219,    0,  219,    0,  214,  191,
      184,    0,    0,  171,  175,  174,  183,  182,  182,  170,
        0,  194,  183,  201,  168,  175,  171,    0,  158,  162,
      169,    0,    0,    0,  159,  172,    0,  188,  154,    0,
        0,    0,  166,    0,  165,  167,  166,  156,  158,  157,
        0,  119,   90,    0,    0,    0,   52,   22,    0,  571,

      243,  248,  253,  258,  261,  266,  270,  273,  276
    } ;

static yyconst short int yy_def[510] =
    {   0,
      500,    1,  501,  501,  502,  502,  503,  503,  500,  500,
      500,  500,  500,  500,  504,  500,  505,  500,  500,  506,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  507,  500,  500,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      504,  500,  508,  500,  500,  500,  500,  500,  506,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,

      509,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  507,  500,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  500,  500,  500,
      500,  500,  508,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  509,  500,  500,  500,  500,  500,  500,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,

      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  500,  500,  500,  500,

      500,  500,  500,  500,  500,  500,  500,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  500,

      500,  500,  500,  500,  500,  500,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  500,  500,  500,  500,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  507,  507,  507,  507,  507,  507,  507,  507,    0,

      500,  500,  500,  500,  500,  500,  500,  500,  500
    } ;

static yyconst short int yy_nxt[647] =
    {   0,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   21,   10,   22,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   33,   34,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   36,   37,   38,   39,   40,
       41,   42,   43,   44,   45,   35,   46,   35,   35,   47,
       35,   48,   49,   50,   35,   51,   52,   53,   54,   55,
       56,   57,   35,   58,   59,   61,   62,   61,   62,   65,
       66,   65,   66,   68,   69,   77,   63,  499,   63,   68,
       69,   75,   76,   81,   82,   98,   83,   91,   84,   78,

       99,   85,   92,   92,  498,  100,   93,   86,   92,   92,
       87,   88,   94,   89,  103,   92,   92,   92,   92,   95,
       96,  108,  109,  110,  111,  115,  133,  159,  104,  105,
      106,  107,  134,  101,  120,  174,  124,  116,  135,  121,
      125,  117,  118,  127,  136,  122,  126,  137,  123,  497,
      138,  143,  128,  129,  130,  144,  146,  139,  140,  147,
      101,  151,  131,  141,  132,  149,  496,  153,  150,   92,
       92,  152,  154,  175,  176,  177,  180,  181,  160,  182,
      191,  192,  194,  183,  184,  185,  197,  205,  213,  198,
      223,  220,  246,  224,  260,  261,  195,  221,  206,  286,

      301,  247,  357,  186,  214,  215,  267,  287,  268,  495,
      494,  269,  493,  492,  491,  490,  489,  488,  487,  486,
      485,  270,  484,  483,  482,  271,  481,  480,  479,  478,
      477,  476,  475,  474,  473,  472,  471,  470,  469,  468,
      302,  467,  358,   60,   60,   60,   60,   60,   64,   64,
       64,   64,   64,   67,   67,   67,   67,   67,   71,   71,
       71,   71,   71,   73,   73,   73,   79,   79,   79,   79,
       79,  112,  112,  112,  163,  163,  163,  173,  173,  466,
      453,  465,  464,  463,  462,  461,  301,  357,  460,  459,
      458,  457,  456,  455,  454,  453,  452,  451,  450,  449,

      448,  447,  446,  445,  444,  443,  442,  441,  440,  439,
      438,  437,  436,  363,  435,  434,  433,  432,  431,  430,
      429,  428,  427,  426,  425,  424,  423,  422,  421,  420,
      419,  418,  417,  416,  415,  414,  413,  412,  411,  410,
      409,  408,  407,  406,  405,  404,  403,  363,  402,  401,
      400,  399,  398,  397,  396,  395,  394,  393,  392,  391,
      390,  389,  388,  387,  386,  385,  384,  383,  382,  381,
      380,  379,  378,  377,  376,  375,  374,  373,  372,  371,
      370,  369,  368,  367,  366,  365,  364,  363,  362,  361,
      360,  359,  356,  355,  354,  353,  352,  351,  350,  349,

      348,  347,  346,  345,  344,  343,  342,  341,  340,  339,
      338,  337,  336,  335,  334,  333,  332,  331,  330,  329,
      328,  327,  326,  325,  324,  323,  322,  321,  320,  319,
      318,  317,  316,  315,  314,  313,  312,  311,  310,  309,
      308,  307,  306,  305,  304,  303,  300,  299,  298,  297,
      296,  295,  294,  293,  292,  291,  290,  289,  288,  285,
      284,  283,  282,  281,  280,  279,  278,  277,  276,  275,
      274,  273,  199,  272,  266,  265,  264,  263,  262,  259,
      258,  257,  256,  255,  254,  253,  252,  251,  250,  249,
      248,  245,  244,  243,  242,  241,  240,  239,  238,  237,

      236,  235,  234,  233,  232,  231,  230,  229,  228,  227,
      226,  225,  222,  219,  218,  217,  216,  212,  211,  210,
      209,  208,  207,  204,  203,  202,  201,  200,  199,  196,
      193,  190,  189,  188,  187,  179,  178,  174,  172,  171,
      170,  169,  168,  167,  166,  165,  164,   80,   72,  162,
      161,  158,  157,  156,  155,  148,  145,  142,  119,  114,
      113,   76,  102,   97,   90,   80,   74,   72,   70,  500,
        9,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,

      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500
    } ;

static yyconst short int yy_chk[647] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    3,    4,    4,    5,
        5,    6,    6,    7,    7,   19,    3,  498,    4,    8,
        8,   18,   18,   21,   21,   27,   21,   23,   21,   19,

       27,   21,   23,   23,  497,   27,   23,   21,   28,   28,
       21,   21,   25,   21,   31,   25,   25,   29,   29,   25,
       25,   32,   32,   33,   33,   39,   44,   59,   31,   31,
       31,   31,   44,   28,   41,  107,   42,   39,   44,   41,
       42,   39,   39,   43,   45,   41,   42,   45,   41,  493,
       46,   48,   43,   43,   43,   48,   50,   46,   46,   50,
       28,   53,   43,   46,   43,   52,  492,   54,   52,   92,
       92,   53,   54,  104,  104,  107,  114,  114,   59,  114,
      120,  120,  122,  114,  114,  114,  124,  132,  140,  124,
      148,  146,  182,  148,  196,  196,  122,  146,  132,  220,

      238,  182,  298,  114,  140,  140,  203,  220,  203,  490,
      489,  203,  488,  487,  486,  485,  483,  479,  478,  476,
      475,  203,  471,  470,  469,  203,  467,  466,  465,  464,
      463,  462,  460,  459,  458,  457,  456,  455,  454,  451,
      238,  450,  298,  501,  501,  501,  501,  501,  502,  502,
      502,  502,  502,  503,  503,  503,  503,  503,  504,  504,
      504,  504,  504,  505,  505,  505,  506,  506,  506,  506,
      506,  507,  507,  507,  508,  508,  508,  509,  509,  449,
      447,  445,  444,  443,  441,  439,  436,  435,  434,  433,
      431,  430,  429,  428,  427,  426,  423,  422,  421,  420,

      417,  416,  415,  414,  413,  412,  411,  410,  409,  407,
      405,  404,  403,  402,  401,  396,  394,  393,  392,  391,
      390,  389,  388,  386,  385,  384,  383,  382,  381,  380,
      378,  377,  376,  375,  374,  373,  372,  371,  370,  369,
      368,  367,  366,  365,  364,  362,  361,  360,  359,  358,
      356,  352,  351,  350,  349,  348,  347,  346,  344,  342,
      341,  340,  339,  338,  337,  336,  334,  333,  332,  330,
      329,  327,  326,  325,  324,  320,  316,  315,  314,  313,
      312,  311,  310,  309,  308,  306,  305,  304,  303,  302,
      300,  299,  297,  296,  295,  294,  293,  292,  291,  290,

      289,  288,  287,  286,  285,  283,  282,  281,  280,  279,
      277,  276,  275,  274,  273,  271,  270,  269,  268,  267,
      266,  265,  263,  262,  261,  260,  259,  258,  257,  256,
      254,  253,  252,  251,  250,  249,  248,  247,  246,  245,
      244,  243,  242,  241,  240,  239,  237,  236,  235,  234,
      232,  229,  227,  226,  225,  224,  223,  222,  221,  218,
      217,  216,  215,  214,  213,  212,  211,  210,  209,  208,
      207,  206,  205,  204,  202,  201,  200,  198,  197,  195,
      194,  193,  192,  191,  190,  189,  187,  186,  185,  184,
      183,  181,  180,  177,  172,  171,  170,  169,  168,  167,

      166,  165,  164,  157,  156,  155,  154,  153,  152,  151,
      150,  149,  147,  144,  143,  142,  141,  139,  137,  136,
      135,  134,  133,  131,  130,  129,  128,  127,  125,  123,
      121,  119,  117,  116,  115,  111,  108,  103,   89,   88,
       87,   86,   85,   84,   83,   82,   81,   79,   71,   70,
       63,   58,   57,   56,   55,   51,   49,   47,   40,   38,
       37,   34,   30,   26,   22,   20,   17,   15,   14,    9,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,

      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#define INITIAL 0

#include "zend_language_parser.h"
#ifdef __cplusplus 
extern "C" YYSTYPE  yylval; 
#endif
extern YYSTYPE  yylval; 

int transfer_token(int id,char copy_value);

#define C_COMMENT 1

#define L_COMMENT 2

#define H_COMMENT 3


/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;




	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 501 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 571 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
{return (int)'<';}
	YY_BREAK
case 2:
YY_RULE_SETUP
{return (int)'>';}
	YY_BREAK
case 3:
YY_RULE_SETUP
{return (int)'!';}
	YY_BREAK
case 4:
YY_RULE_SETUP
{return (int)'^';}
	YY_BREAK
case 5:
YY_RULE_SETUP
{return (int)'&';}
	YY_BREAK
case 6:
YY_RULE_SETUP
{return (int)'|';}
	YY_BREAK
case 7:
YY_RULE_SETUP
{return (int)'=';}
	YY_BREAK
case 8:
YY_RULE_SETUP
{return (int)'*';}
	YY_BREAK
case 9:
YY_RULE_SETUP
{return (int)'+';}
	YY_BREAK
case 10:
YY_RULE_SETUP
{return (int)'-';}
	YY_BREAK
case 11:
YY_RULE_SETUP
{return (int)'/';}
	YY_BREAK
case 12:
YY_RULE_SETUP
{return (int)'%';}
	YY_BREAK
case 13:
YY_RULE_SETUP
{return (int)'.';}
	YY_BREAK
case 14:
YY_RULE_SETUP
{return (int)',';}
	YY_BREAK
case 15:
YY_RULE_SETUP
{return T_CLASS;}
	YY_BREAK
case 16:
YY_RULE_SETUP
{return T_REQUIRE_ONCE;}
	YY_BREAK
case 17:
YY_RULE_SETUP
{return T_REQUIRE;}
	YY_BREAK
case 18:
YY_RULE_SETUP
{return T_EVAL;}
	YY_BREAK
case 19:
YY_RULE_SETUP
{return T_INCLUDE_ONCE;}
	YY_BREAK
case 20:
YY_RULE_SETUP
{return T_INCLUDE;}
	YY_BREAK
case 21:
YY_RULE_SETUP
{return T_LOGICAL_OR;}
	YY_BREAK
case 22:
YY_RULE_SETUP
{return T_LOGICAL_XOR;}
	YY_BREAK
case 23:
YY_RULE_SETUP
{return T_LOGICAL_AND;}
	YY_BREAK
case 24:
YY_RULE_SETUP
{return T_PRINT;}
	YY_BREAK
case 25:
YY_RULE_SETUP
{return T_SR_EQUAL;}
	YY_BREAK
case 26:
YY_RULE_SETUP
{return T_SL_EQUAL;}
	YY_BREAK
case 27:
YY_RULE_SETUP
{return T_XOR_EQUAL;}
	YY_BREAK
case 28:
YY_RULE_SETUP
{return T_OR_EQUAL;}
	YY_BREAK
case 29:
YY_RULE_SETUP
{return T_AND_EQUAL;}
	YY_BREAK
case 30:
YY_RULE_SETUP
{return T_MOD_EQUAL;}
	YY_BREAK
case 31:
YY_RULE_SETUP
{return T_CONCAT_EQUAL;}
	YY_BREAK
case 32:
YY_RULE_SETUP
{return T_DIV_EQUAL;}
	YY_BREAK
case 33:
YY_RULE_SETUP
{return T_MUL_EQUAL;}
	YY_BREAK
case 34:
YY_RULE_SETUP
{return T_MINUS_EQUAL;}
	YY_BREAK
case 35:
YY_RULE_SETUP
{return T_PLUS_EQUAL;}
	YY_BREAK
case 36:
YY_RULE_SETUP
{return T_BOOLEAN_OR;}
	YY_BREAK
case 37:
YY_RULE_SETUP
{return T_BOOLEAN_AND;}
	YY_BREAK
case 38:
YY_RULE_SETUP
{return T_IS_NOT_IDENTICAL;}
	YY_BREAK
case 39:
YY_RULE_SETUP
{return T_IS_IDENTICAL;}
	YY_BREAK
case 40:
YY_RULE_SETUP
{return T_IS_NOT_EQUAL;}
	YY_BREAK
case 41:
YY_RULE_SETUP
{return T_IS_EQUAL;}
	YY_BREAK
case 42:
YY_RULE_SETUP
{return T_IS_GREATER_OR_EQUAL;}
	YY_BREAK
case 43:
YY_RULE_SETUP
{return T_SL;}
	YY_BREAK
case 44:
YY_RULE_SETUP
{return T_IS_SMALLER_OR_EQUAL;}
	YY_BREAK
case 45:
YY_RULE_SETUP
{return T_SR;}
	YY_BREAK
case 46:
YY_RULE_SETUP
{return T_INSTANCEOF;}
	YY_BREAK
case 47:
YY_RULE_SETUP
{return T_UNSET_CAST;}
	YY_BREAK
case 48:
YY_RULE_SETUP
{return T_BOOL_CAST;}
	YY_BREAK
case 49:
YY_RULE_SETUP
{return T_OBJECT_CAST;}
	YY_BREAK
case 50:
YY_RULE_SETUP
{return T_ARRAY_CAST;}
	YY_BREAK
case 51:
YY_RULE_SETUP
{return T_STRING_CAST;}
	YY_BREAK
case 52:
YY_RULE_SETUP
{return T_DOUBLE_CAST;}
	YY_BREAK
case 53:
YY_RULE_SETUP
{return T_INT_CAST;}
	YY_BREAK
case 54:
YY_RULE_SETUP
{return T_DEC;}
	YY_BREAK
case 55:
YY_RULE_SETUP
{return T_INC;}
	YY_BREAK
case 56:
YY_RULE_SETUP
{return T_CLONE;}
	YY_BREAK
case 57:
YY_RULE_SETUP
{return T_NEW;}
	YY_BREAK
case 58:
YY_RULE_SETUP
{return T_EXIT;}
	YY_BREAK
case 59:
YY_RULE_SETUP
{return T_IF;}
	YY_BREAK
case 60:
YY_RULE_SETUP
{return T_ELSEIF;}
	YY_BREAK
case 61:
YY_RULE_SETUP
{return T_ELSE;}
	YY_BREAK
case 62:
YY_RULE_SETUP
{return T_ENDIF;}
	YY_BREAK
case 63:
YY_RULE_SETUP
{return T_LNUMBER;}
	YY_BREAK
case 64:
YY_RULE_SETUP
{return T_LNUMBER;}
	YY_BREAK
case 65:
YY_RULE_SETUP
{return T_DNUMBER;}
	YY_BREAK
case 66:
YY_RULE_SETUP
{return T_STRING_VARNAME;}
	YY_BREAK
case 67:
YY_RULE_SETUP
{return T_NUM_STRING;}
	YY_BREAK
case 68:
YY_RULE_SETUP
{return T_ENCAPSED_AND_WHITESPACE;}
	YY_BREAK
case 69:
YY_RULE_SETUP
{return T_CONSTANT_ENCAPSED_STRING;}
	YY_BREAK
case 70:
YY_RULE_SETUP
{return T_CONSTANT_ENCAPSED_STRING;}
	YY_BREAK
case 71:
YY_RULE_SETUP
{return T_ECHO;}
	YY_BREAK
case 72:
YY_RULE_SETUP
{return T_DO;}
	YY_BREAK
case 73:
YY_RULE_SETUP
{return T_WHILE;}
	YY_BREAK
case 74:
YY_RULE_SETUP
{return T_ENDWHILE;}
	YY_BREAK
case 75:
YY_RULE_SETUP
{return T_FOR;}
	YY_BREAK
case 76:
YY_RULE_SETUP
{return T_ENDFOR;}
	YY_BREAK
case 77:
YY_RULE_SETUP
{return T_FOREACH;}
	YY_BREAK
case 78:
YY_RULE_SETUP
{return T_ENDFOREACH;}
	YY_BREAK
case 79:
YY_RULE_SETUP
{return T_DECLARE;}
	YY_BREAK
case 80:
YY_RULE_SETUP
{return T_ENDDECLARE;}
	YY_BREAK
case 81:
YY_RULE_SETUP
{return T_AS;}
	YY_BREAK
case 82:
YY_RULE_SETUP
{return T_SWITCH;}
	YY_BREAK
case 83:
YY_RULE_SETUP
{return T_ENDSWITCH;}
	YY_BREAK
case 84:
YY_RULE_SETUP
{return T_CASE;}
	YY_BREAK
case 85:
YY_RULE_SETUP
{return T_DEFAULT;}
	YY_BREAK
case 86:
YY_RULE_SETUP
{return T_BREAK;}
	YY_BREAK
case 87:
YY_RULE_SETUP
{return T_CONTINUE;}
	YY_BREAK
case 88:
YY_RULE_SETUP
{return T_GOTO;}
	YY_BREAK
case 89:
YY_RULE_SETUP
{return T_FUNCTION;}
	YY_BREAK
case 90:
YY_RULE_SETUP
{return T_CONST;}
	YY_BREAK
case 91:
YY_RULE_SETUP
{return T_RETURN;}
	YY_BREAK
case 92:
YY_RULE_SETUP
{return T_TRY;}
	YY_BREAK
case 93:
YY_RULE_SETUP
{return T_CATCH;}
	YY_BREAK
case 94:
YY_RULE_SETUP
{return T_THROW;}
	YY_BREAK
case 95:
YY_RULE_SETUP
{return T_USE;}
	YY_BREAK
case 96:
YY_RULE_SETUP
{return T_GLOBAL;}
	YY_BREAK
case 97:
YY_RULE_SETUP
{return T_PUBLIC;}
	YY_BREAK
case 98:
YY_RULE_SETUP
{return T_PROTECTED;}
	YY_BREAK
case 99:
YY_RULE_SETUP
{return T_PRIVATE;}
	YY_BREAK
case 100:
YY_RULE_SETUP
{return T_FINAL;}
	YY_BREAK
case 101:
YY_RULE_SETUP
{return T_ABSTRACT;}
	YY_BREAK
case 102:
YY_RULE_SETUP
{return T_STATIC;}
	YY_BREAK
case 103:
YY_RULE_SETUP
{return T_VAR;}
	YY_BREAK
case 104:
YY_RULE_SETUP
{return T_UNSET;}
	YY_BREAK
case 105:
YY_RULE_SETUP
{return T_ISSET;}
	YY_BREAK
case 106:
YY_RULE_SETUP
{return T_EMPTY;}
	YY_BREAK
case 107:
YY_RULE_SETUP
{return T_INTERFACE;}
	YY_BREAK
case 108:
YY_RULE_SETUP
{return T_EXTENDS;}
	YY_BREAK
case 109:
YY_RULE_SETUP
{return T_IMPLEMENTS;}
	YY_BREAK
case 110:
YY_RULE_SETUP
{return T_OBJECT_OPERATOR;}
	YY_BREAK
case 111:
YY_RULE_SETUP
{return T_DOUBLE_ARROW;}
	YY_BREAK
case 112:
YY_RULE_SETUP
{return T_LIST;}
	YY_BREAK
case 113:
YY_RULE_SETUP
{return T_ARRAY;}
	YY_BREAK
case 114:
YY_RULE_SETUP
{return T_HALT_COMPILER;}
	YY_BREAK
case 115:
YY_RULE_SETUP
{return T_CLASS_C;}
	YY_BREAK
case 116:
YY_RULE_SETUP
{return T_METHOD_C;}
	YY_BREAK
case 117:
YY_RULE_SETUP
{return T_FUNC_C;}
	YY_BREAK
case 118:
YY_RULE_SETUP
{return T_LINE;}
	YY_BREAK
case 119:
YY_RULE_SETUP
{return T_FILE;}
	YY_BREAK
case 120:
YY_RULE_SETUP
{return T_NAMESPACE;}
	YY_BREAK
case 121:
YY_RULE_SETUP
{return T_NS_C;}
	YY_BREAK
case 122:
YY_RULE_SETUP
{return T_DIR;}
	YY_BREAK
case 123:
YY_RULE_SETUP
{return transfer_token(T_STRING,1);}
	YY_BREAK
case 124:
YY_RULE_SETUP
{return transfer_token(T_VARIABLE,1);}
	YY_BREAK
case 125:
YY_RULE_SETUP
{return T_DOC_COMMENT;}
	YY_BREAK
case 126:
YY_RULE_SETUP
{;}
	YY_BREAK
case 127:
YY_RULE_SETUP
{;}
	YY_BREAK
case 128:
YY_RULE_SETUP
{;}
	YY_BREAK
case 129:
YY_RULE_SETUP
{return T_START_HEREDOC;}
	YY_BREAK
case 130:
YY_RULE_SETUP
{return T_END_HEREDOC;}
	YY_BREAK
case 131:
YY_RULE_SETUP
{return T_DOLLAR_OPEN_CURLY_BRACES;}
	YY_BREAK
case 132:
YY_RULE_SETUP
{return T_CURLY_OPEN;}
	YY_BREAK
case 133:
YY_RULE_SETUP
{return T_PAAMAYIM_NEKUDOTAYIM;}
	YY_BREAK
case 134:
YY_RULE_SETUP
{return T_NS_SEPARATOR;}
	YY_BREAK
case 135:
YY_RULE_SETUP
{ BEGIN(C_COMMENT); }
	YY_BREAK
case 136:
YY_RULE_SETUP
{ BEGIN(INITIAL); }
	YY_BREAK
case 137:
YY_RULE_SETUP
{ printf("%c",yytext[0]); }
	YY_BREAK
case 138:
YY_RULE_SETUP
{ printf("\n"); }
	YY_BREAK
case 139:
YY_RULE_SETUP
{ BEGIN(L_COMMENT); }
	YY_BREAK
case 140:
YY_RULE_SETUP
{ printf("\n");BEGIN(INITIAL); }
	YY_BREAK
case 141:
YY_RULE_SETUP
{ printf("%c",yytext[0]); }
	YY_BREAK
case 142:
YY_RULE_SETUP
{ BEGIN(H_COMMENT); }
	YY_BREAK
case 143:
YY_RULE_SETUP
{ printf("\n");BEGIN(INITIAL); }
	YY_BREAK
case 144:
YY_RULE_SETUP
{ printf("%c",yytext[0]);; }
	YY_BREAK
case 145:
YY_RULE_SETUP
{;}
	YY_BREAK
case 146:
YY_RULE_SETUP
{;;}
	YY_BREAK
case 147:
YY_RULE_SETUP
{return (int)yytext[0];}
	YY_BREAK
case 148:
YY_RULE_SETUP
ECHO;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(C_COMMENT):
case YY_STATE_EOF(L_COMMENT):
case YY_STATE_EOF(H_COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 501 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 501 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 500);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif


int transfer_token(int id,char copy_value)
{
  if(copy_value)
  {
    yylval.val=malloc(yyleng+1);
    sprintf(yylval.val,"%s\0",yytext);
  }
  return id;
}

#ifndef yywrap
yywrap()
{ return 1; }
#endif